/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */

import "sst";
export {};
declare module "sst" {
  export interface Resource {
    NextEmail: {
      type: "sst.aws.Email";
      sender: string;
    };
    SupportEmail: {
      type: "sst.aws.Email";
      sender: string;
    };
  }
}
